title:              Blog
email:              your-email@example.com
description:        Here are our posts
author:             The itHelp Project
#baseurl:            ""
url:                "https://prohack17.github.io/" 

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
